from tkinter import*
root=Tk()
root.title("Learn to code here")
frame=LabelFrame(root, text="This is my frame",padx=10,pady=10)
frame.pack(padx=10,pady=10)
b=Button(frame, text="Dont click here")
b.grid(row=0,column=0)
b2=Button(frame, text="..or here")
b2.grid(row=1,column=0)
root.mainloop()